site_name: Shapeshifter specification
repo_url: https://github.com/shapeshifter/shapeshifter-specification
site_url: http://localhost:8000/
theme:
  name: material
  features:
    - content.action.edit
    - navigation.indexes
  logo: assets/images/shapeshifter-icon-white.svg
  favicon: assets/images/shapeshifter-icon-color.svg
plugins:
  - search
  - pdf-generate:
      author: "Shapeshifter contributors"
      # author_logo: img/logo.svg
      copyright: "Copyright © 2023 - Shapeshifter authors"
      disclaimer: "Disclaimer: Content can change at anytime and best to refer to website for latest information."
      # cover: true
      cover_title: TITLE TEXT
      cover_subtitle: SUBTITLE TEXT
      custom_template_path: TEMPLATES PATH
      toc: false
      toc_level: 3
      toc_title: TOC TITLE TEXT
      toc_numbering: true
      # cover_images:
      #   default: img/default.svg
      #   type1: img/type1.png
      #   type2: https://example.com/cover.svg
      enabled_if_env: ENABLE_PDF_EXPORT
markdown_extensions:
  - admonition

nav:
  - USEF Flex Trading Protocol: usef-flex-trading-protocol.md
  - About UFTP:
      - Purpose: about/purpose.md
      - Scope: about/scope.md
      - Levels of compliancy: about/levels-of-compliancy.md
      - Reading guideline: about/reading-guideline.md
  - General description:
      - general-description/index.md
      - USEF general concepts: general-description/usef-general-concepts.md
      - Contract phase: general-description/contract-phase.md
      - Plan phase: general-description/plan-phase.md
      - Validate phase: general-description/validate-phase.md
      - Operate phase: general-description/operate-phase.md
      - Settle phase: general-description/settle-phase.md
  - Use case descriptions:
      - Scope: use-case-descriptions/scope.md
      - Privacy and security by design: use-case-descriptions/privacy-and-security-by-design.md
      - Common concepts: use-case-descriptions/common-concepts.md
      - Reading guidelines: use-case-descriptions/reading-guidelines.md
      - Message validation: use-case-descriptions/message-validation.md
      - Use Cases:
          - Contract phase: use-case-descriptions/use-cases/contract-phase.md
          - Plan phase: use-case-descriptions/use-cases/plan-phase.md
          - Validate phase: use-case-descriptions/use-cases/validate-phase.md
          - Operate phase: use-case-descriptions/use-cases/operate-phase.md
          - Settle phase: missing.md
  - Message description:
      - Scope: missing.md
      - Message catalog: missing.md
  - Appendix:
      - Glossary: missing.md
      - Rationale for information exchange in flexiblity request: missing.md
      - Flex reservation mechanism: missing.md
      - Message transport mechanism: missing.md
      - Bibliography: missing.md
